export const initParams = [
  {
    name: "Default",
    value: {
      styles:{
        baseColor: "black",
        backgroundColor:"#181818",
        accentColor:"#FFFFFF",
        accentRGBAColor:"#FFFFFF1A",
        primaryColor:"#bb1414",//red
        secondaryColor:"#ffa322",//yellow,
      },
      logo:"https://donkeyclip.github.io/sports-clip/demo/assets/logo.png",
      audio:"https://donkeyclip.github.io/sports-clip/demo/assets/sportsAudio.mp3",
      intro:{
        name:["MANCHESTER","UNITED"],
        subtitle:["team","intro"]
      },
      players:[
        {
          number:"01",
          firstname:"David",
          lastname:"De Gea",
          img:"https://donkeyclip.github.io/sports-clip/demo/assets/davidDeGea.png"
        },
        {
          number:"05",
          firstname:"Harry",
          lastname:"Maguire",
          img:"https://donkeyclip.github.io/sports-clip/demo/assets/harry.png"
        },
        {
          number:"06",
          firstname:"Paul",
          lastname:"Pogba",
          img:"https://donkeyclip.github.io/sports-clip/demo/assets/pogba.png"
        },
        {
          number:"07",
          firstname:"Cristiano",
          lastname:"Ronaldo",
          img:"https://donkeyclip.github.io/sports-clip/demo/assets/ronaldo.png"
        },
        {
          number:"10",
          firstname:"Marcus",
          lastname:"Rashford",
          img:"https://donkeyclip.github.io/sports-clip/demo/assets/rashford.png"
        },
        {
          number:"18",
          firstname:"Bruno",
          lastname:"Fernandes",
          img:"https://donkeyclip.github.io/sports-clip/demo/assets/bruno.png"
        }
      ],
    },
  },
];
